language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - poetry run flake8 replace_with_gkg
  - make -C docs/ html
  - touch docs/build/html/.nojekyll
deploy:
  - provider: pages
    token: $GITHUB_TOKEN
    skip_cleanup: true
    keep_history: true
    local_dir: ./docs/build/html/
    on:
      branch: master
